import type { Project } from '../../shared/types';

export const projects: readonly Project[] = [
    {
        id: 'earthbank',
        title: 'Earthbank',
        description: 'Mobile UI Project for waste bank',
        category: 'UI/UX Design',
        thumbnail: '/public/projects/earthbank-1.webp',
        gallery: ['/public/projects/earthbank-1.webp', '/public/projects/earthbank-2.webp', '/public/projects/earthbank-3.webp', '/public/projects/earthbank-4.webp'],
        tags: ['Figma', 'Design Thinking', 'Design System', 'Wireframing', 'Prototyping'],
        liveUrl: 'https://www.figma.com/proto/NbDdOex8akm9akvEVhdbG3/P16-IMK?node-id=22-278&t=4wRTkej2LnDB4EkZ-1',
        featured: true,
        archived: false,
    },
    {
        id: 'finance-api',
        title: 'Finance API',
        description: 'A simple API for finance tracking, learned a lot to backend to this project',
        category: 'Backend',
        thumbnail: '/public/projects/finance-api-1.webp',
        gallery: ['/public/projects/finance-api-1.webp', '/public/projects/finance-api-2.webp', '/public/projects/finance-api-3.webp'],
        tags: ['TypeScript', 'React', 'Node', 'MongoDB'],
        repoUrl: 'https://github.com/sayyidrafeed/finance-api',
        featured: true,
        archived: false,
    },
    {
        id: 'dirka-upnvj',
        title: 'DIRKA UPNVJ',
        description: 'A simple canteen web app for UPNVJ, build for members of UPNVJ to see the menu and feedback',
        category: 'Fullstack',
        thumbnail: '/public/projects/dirka-upnvj-1.webp',
        gallery: ['/public/projects/dirka-upnvj-1.webp', '/public/projects/dirka-upnvj-2.webp', '/public/projects/dirka-upnvj-3.webp', '/public/projects/dirka-upnvj-4.webp'],
        tags: ['PHP', 'MySQL'],
        repoUrl: 'https://github.com/sayyidrafeed/kantin-upnvj',
        featured: true,
        archived: false,
    },
    {
        id: 'portfolio',
        title: 'This Portfolio',
        description: 'Build with vibe coding, my experimental environment',
        category: 'Frontend',
        thumbnail: '/public/projects/portfolio-1.webp',
        gallery: ['/public/projects/portfolio-1.webp'],
        tags: ['TypeScript', 'Bun', 'Svelte', 'TailwindCSS', 'Vite'],
        // liveUrl: 'soon',
        repoUrl: 'https://github.com/sayyidrafeed/rafee-portfolio',
        featured: true,
        archived: false,
    },
] as const;
