import type { Project } from '../../shared/types';

export const projects: readonly Project[] = [
    {
        id: 'project-alpha',
        title: 'Project Alpha',
        description: 'A cutting-edge web application built with modern technologies and best practices.',
        thumbnail: '/projects/alpha-thumb.webp',
        gallery: ['/projects/alpha-1.webp', '/projects/alpha-2.webp'],
        techStack: ['TypeScript', 'Svelte', 'TailwindCSS', 'Vite'],
        liveUrl: 'https://alpha.example.com',
        repoUrl: 'https://github.com/rafee/alpha',
        featured: true,
        archived: false,
    },
    {
        id: 'project-beta',
        title: 'Project Beta',
        description: 'An innovative platform that pushes the boundaries of user experience.',
        thumbnail: '/projects/beta-thumb.webp',
        gallery: ['/projects/beta-1.webp'],
        techStack: ['TypeScript', 'React', 'Node', 'PostgreSQL'],
        liveUrl: 'https://beta.example.com',
        repoUrl: 'https://github.com/rafee/beta',
        featured: true,
        archived: false,
    },
    {
        id: 'project-gamma',
        title: 'Project Gamma',
        description: 'A high-performance API built for scale and reliability.',
        thumbnail: '/projects/gamma-thumb.webp',
        gallery: [],
        techStack: ['Go', 'PostgreSQL', 'Redis', 'Docker'],
        repoUrl: 'https://github.com/rafee/gamma',
        featured: false,
        archived: false,
    },
    {
        id: 'project-delta',
        title: 'Project Delta',
        description: 'An experimental project exploring new paradigms in web development.',
        thumbnail: '/projects/delta-thumb.webp',
        gallery: ['/projects/delta-1.webp'],
        techStack: ['Rust', 'TypeScript', 'Bun'],
        featured: false,
        archived: false,
    },
] as const;
