import type { Project } from '../../shared/types';

export const projects: readonly Project[] = [
    {
        id: 'earthbank',
        title: 'Earthbank',
        description: 'Mobile UI Project for waste bank',
        thumbnail: '/projects/earthbank-thumb.webp',
        gallery: ['/projects/earthbank-1.webp', '/projects/earthbank-2.webp'],
        techStack: ['TypeScript', 'Svelte', 'TailwindCSS', 'Vite'],
        liveUrl: 'https://alpha.example.com',
        repoUrl: 'https://github.com/rafee/alpha',
        featured: true,
        archived: false,
    },
    {
        id: 'finance-api',
        title: 'Finance API',
        description: 'A simple API for finance tracking, learned a lot to backend to this project',
        thumbnail: '/projects/finance-api-thumb.webp',
        gallery: ['/projects/finance-api-1.webp'],
        techStack: ['TypeScript', 'React', 'Node', 'PostgreSQL'],
        repoUrl: 'https://github.com/sayyidrafeed/finance-api',
        featured: true,
        archived: false,
    },
    {
        id: 'dirka-upnvj',
        title: 'DIRKA UPNVJ',
        description: 'A simple canteen web app for UPNVJ, build for members of UPNVJ to see the menu and feedback',
        thumbnail: '/projects/dirka-upnvj-thumb.webp',
        gallery: ['/projects/dirka-upnvj-1.webp', '/projects/dirka-upnvj-2.webp'],
        techStack: ['PHP', 'MySQL'],
        repoUrl: 'https://github.com/sayyidrafeed/kantin-upnvj',
        featured: false,
        archived: false,
    },
    {
        id: 'portfolio',
        title: 'This Portfolio',
        description: 'Build with vibe coding, my experimental environment',
        thumbnail: '/projects/portfolio-thumb.webp',
        gallery: ['/projects/portfolio-1.webp', '/projects/portfolio-2.webp'],
        techStack: ['TypeScript', 'Bun', 'Svelte', 'TailwindCSS', 'Vite'],
        // liveUrl: 'soon',
        repoUrl: 'https://github.com/sayyidrafeed/rafee-portfolio',
        featured: false,
        archived: false,
    },
] as const;
